version: "3.1"

volumes:
  metadata_var: {}
  middle_var: {}
  historical_var: {}
  broker_var: {}
  coordinator_var: {}
  router_var: {}
  druid_var: {}

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - metadata_var:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=druid
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid
 
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 5

  coordinator:
    image: apache/druid:0.22.0
    container_name: coordinator
    volumes:
      - druid_var:/var/druid
      - coordinator_var:/var/druid
    depends_on:
      - zookeeper
      - postgres
    ports:
      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment_coordinator

  broker:
    image: apache/druid:0.22.0
    container_name: broker
    volumes:
      - broker_var:/var/druid
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8082:8082"
    command:
      - broker
    env_file:
      - environment_broker

  historical:
    image: apache/druid:0.22.0
    container_name: historical
    volumes:
      - druid_var:/var/druid
      - historical_var:/var/druid
    depends_on: 
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8083:8083"
    command:
      - historical
    env_file:
      - environment_historical

  middlemanager:
    image: apache/druid:0.22.0
    container_name: middlemanager
    volumes:
      - druid_var:/var/druid
      - middle_var:/var/druid
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8091:8091"
      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - environment_middlemanager

  router:
    image: apache/druid:0.22.0
    container_name: router
    volumes:
      - router_var:/var/druid
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment_router