version: "3.1"

services:
  zookeeper1:
    container_name: zookeeper1
    image: zookeeper:3.6.3
    ports:
      - "2182:2182"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOO_MY_ID: 6
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 5
      ZOO_CFG_EXTRA: "clientPort=2182"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.29.3
      KAFKA_BROKER_ID: 6
      KAFKA_LOG_DIR: /logs
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2182
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.29.3:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "portal_customers:3:1,portal_merchants:3:1,portal_stores:3:1,portal_tpns:3:1,portal_device_models:3:1,portal_tx_bases:3:1,portal_tx_alternate:3:1:compact"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper1